apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: ctscheduler
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - pods/binding
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  - csidrivers
  - csistoragecapacities
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - statefulsets
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  - namespaces
  - configmaps
  - replicationcontrollers
  - persistentvolumes
  - poddisruptionbudgets
  - replicasets
  - statefulsets
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - watch
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: ct-scheduler
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: ctscheduler
subjects:
- kind: ServiceAccount
  name: ct-scheduler
  namespace: kube-system
